name: dataset-edna
channels:
  - defaults
dependencies:
  - biopython=1.78=py38h9ed2024_0
  - blas=1.0=mkl
  - bottleneck=1.3.2=py38hf1fa96c_1
  - ca-certificates=2021.10.26=hecd8cb5_2
  - certifi=2021.10.8=py38hecd8cb5_0
  - intel-openmp=2021.4.0=hecd8cb5_3538
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - mkl=2021.4.0=hecd8cb5_637
  - mkl-service=2.4.0=py38h9ed2024_0
  - mkl_fft=1.3.1=py38h4ab4a9b_0
  - mkl_random=1.2.2=py38hb2f4e1b_0
  - ncurses=6.3=hca72f7f_2
  - numexpr=2.7.3=py38h5873af2_1
  - numpy=1.21.2=py38h4b4dc7a_0
  - numpy-base=1.21.2=py38he0bd621_0
  - openssl=1.1.1l=h9ed2024_0
  - pandas=1.3.4=py38h743cdd8_0
  - pip=21.2.4=py38hecd8cb5_0
  - python=3.8.12=h88f2d9e_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - readline=8.1=h9ed2024_0
  - setuptools=58.0.4=py38hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hce871da_0
  - tk=8.6.11=h7bc2e8c_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/dianalg/miniconda3/envs/dataset-edna
